language: php

matrix:
  fast_finish: true
  include:
  - php: 7.1
  - php: 7.2

sudo: false

install:
  - travis_retry composer install

script:
  - composer ci

cache:
  directories:
  - "$HOME/.composer/cache"

notifications:
  email:
    on_success: change
    on_failure: always