CREATE TABLE `ticket` (
  `id`                       BIGINT(20)  NOT NULL,
  `tn`                       VARCHAR(50) NOT NULL,
  `title`                    VARCHAR(255)         DEFAULT NULL,
  `queue_id`                 INT(11)     NOT NULL,
  `ticket_lock_id`           SMALLINT(6) NOT NULL,
  `type_id`                  SMALLINT(6)          DEFAULT NULL,
  `service_id`               INT(11)              DEFAULT NULL,
  `sla_id`                   INT(11)              DEFAULT NULL,
  `user_id`                  INT(11)     NOT NULL,
  `responsible_user_id`      INT(11)     NOT NULL,
  `ticket_priority_id`       SMALLINT(6) NOT NULL,
  `ticket_state_id`          SMALLINT(6) NOT NULL,
  `customer_id`              VARCHAR(150)         DEFAULT NULL,
  `customer_user_id`         VARCHAR(250)         DEFAULT NULL,
  `timeout`                  INT(11)     NOT NULL,
  `until_time`               INT(11)     NOT NULL,
  `escalation_time`          INT(11)     NOT NULL,
  `escalation_update_time`   INT(11)     NOT NULL,
  `escalation_response_time` INT(11)     NOT NULL,
  `escalation_solution_time` INT(11)     NOT NULL,
  `archive_flag`             SMALLINT(6) NOT NULL DEFAULT '0',
  `create_time_unix`         BIGINT(20)  NOT NULL,
  `create_time`              TEXT    NOT NULL,
  `create_by`                INT(11)     NOT NULL,
  `change_time`              TEXT    NOT NULL,
  `change_by`                INT(11)     NOT NULL,
  PRIMARY KEY (`id`)
);